### ISSUE TITLE
Error: ./libmpow.so: undefined symbol: blake2b_init

### ISSUE THREAD

**Issue by admirabilis** [jamescoxon/nano_distributed_pow_client#10]
All steps work, but running `python3 client.py` fails with 

```
You have selected local PoW processor (libmpow)
Waiting for work...
Got work
Error: ./libmpow.so: undefined symbol: blake2b_init
```

Tested on Ubuntu 16.04 (libb2-1 and libb2-dev 0.97-4\~ubuntu16.04.1~ppa2) and 18.04 (libb2-1 and libb2-dev 0.97+git20171226-2).

**Comment by guilhermelawless** [comment]
Thanks, latest `master` should fix it. Start again from `autoconf`

**Comment by admirabilis** [comment]
Works! Thanks!
