### ISSUE TITLE
Performance for computing by node vs using the library, for a GPU

### ISSUE THREAD

**Issue by guilhermelawless** [jamescoxon/nano_distributed_pow_client#16]
Since a CPU is slow for blake2b the overhead is irrelevant.

Currently the library will de-allocate and re-allocate the memory for computing blake2b's for each hash. If we are to minimize delays for the clients, especially for **urgent** hashes, then this can make an impact.

In branch [performance-check](https://github.com/jamescoxon/nano_distributed_pow_client/tree/performance-check) there is a timeit wrapper for both methods, please report your results below.

**Comment by guilhermelawless** [comment]
With a GTX 1070, 100 works each:

> RESULTS
        Node: 51.124615304986946
        Library: 71.07404277904425

Library calls currently 40% slower on average, in my case.

**Comment by ghost** [comment]
Blake2b libraries are required only in the CPU mode. In the GPU mode, blake hashes are computed using the same kernel that the node uses. So the difference is not there. It's possibly in some other part. I've to check.

**Comment by guilhermelawless** [comment]
Oh I see. With nano-work-server I have a constant 1% memory being used by the GPU. Our library doesn't reserve anything. Could this be a significant overhead?

**Comment by ghost** [comment]
I'm not sure. I'll take a look at this later. But quick note, I noticed that you branched this from master. Can you try the same wrapper with the updated pip branch? That should improve things slightly. Do take a look at the README. Instructions and package dependencies are slightly different.

**Comment by guilhermelawless** [comment]
See #14

**Comment by guilhermelawless** [comment]
> RESULTS
>         Node: 61.93995178397745
>         Library: 67.2685250909999

That's much closer, 8% slower only.

**Comment by guilhermelawless** [comment]
@nano128  new results

- I have taken care to not have anything else on the GPU (there was previously)
- Generated 3000 on each method

> Computing 3000 works using the node.
Computing 3000 works using the library

> RESULTS
        Node: 1647.4275898939231
        Library: 2088.526867095963

27% slower. I think you will really have to keep everything in memory to improve.

**Comment by ghost** [comment]
A server like implementation has the advantage of keeping the GPU alive with buffers already allocated. Whereas for the extension, memory has to be reallocated and emptied for each call. This overhead is the difference we noticed.

https://github.com/nano128/nano-work-server

is a server mode variation of the extension. With the overhead taken out performance is comparable.
